# Generated by Django 6.0.4 on 2026-05-05 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_kilo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_in_sacks',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave')], default='present', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Supplier of feeds for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('livestock', 'Cebuana Padala'), ('agripet', 'AgriPet Store')], max_length=16),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
