# Generated by Django 6.0.4 on 2026-05-06 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('send', 'Send Money'), ('receive', 'Receive Money'), ('bills', 'Bills Payment'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='store.store')),
            ],
            options={
                'verbose_name': 'Service Transaction',
                'verbose_name_plural': 'Service Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
