# Generated by Django 6.0.5 on 2026-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_servicetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('livestock', 'Cebuana Padala'), ('agripet', 'AgriPet Store')], max_length=16, unique=True),
        ),
    ]
